// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"golang_grafana_struct/infra"
	"golang_grafana_struct/passage"
	"golang_grafana_struct/passage/database"
	"golang_grafana_struct/passage/service"
)

// Injectors from init_wire.go:

func InitializePassageService() (passage.PassageService, error) {
	idb := db.ProvideDb()
	store, err := database.ProvidePassageStore(idb)
	if err != nil {
		return nil, err
	}
	passageService := service.ProvidePassageService(store)
	return passageService, nil
}

// init_wire.go:

var wireBasicSet = wire.NewSet(db.ProvideDb, database.ProvidePassageStore, service.ProvidePassageService)
